/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
!!GlobalInfo
product: Pins v12.0
processor: MKE16Z64xxx4
package_id: MKE16Z64VLD4
mcu_data: ksdk2_0
processor_version: 12.0.0
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

#include "fsl_common.h"
#include "fsl_port.h"
#include "fsl_trgmux.h"
#include "pin_mux.h"

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitBootPins
 * Description   : Calls initialization functions.
 *
 * END ****************************************************************************************************************/
void BOARD_InitBootPins(void)
{
    BOARD_InitPins();
}

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
BOARD_InitPins:
- options: {callFromInitBoot: 'true', coreID: core0, enableClock: 'true'}
- pin_list:
  - {pin_num: '32', peripheral: LPI2C0, signal: SCL, pin_signal: PTA3/LPI2C0_SCL/EWM_IN/LPUART0_TX}
  - {pin_num: '33', peripheral: LPI2C0, signal: SDA, pin_signal: PTA2/LPI2C0_SDA/EWM_OUT_b/LPUART0_RX}
  - {pin_num: '44', peripheral: CoreDebug, signal: SWD_DIO, pin_signal: PTA4/ACMP0_OUT/EWM_OUT_b/SWD_DIO}
  - {pin_num: '42', peripheral: CoreDebug, signal: SWD_CLK, pin_signal: ACMP0_IN2/PTC4/FTM1_CH0/RTC_CLKOUT/EWM_IN/FTM1_QD_PHB/SWD_CLK}
  - {pin_num: '35', peripheral: GPIOA, signal: 'GPIO, 0', pin_signal: ADC0_SE0/ACMP0_IN0/TSI0_CH17/PTA0/LPI2C0_SCLS/LPUART0_CTS/TRGMUX_OUT3}
  - {pin_num: '34', peripheral: LPI2C0, signal: MASTER_STOP, pin_signal: ADC0_SE1/ACMP0_IN1/TSI0_CH18/PTA1/FTM1_CH1/LPI2C0_SDAS/FTM1_QD_PHA/LPUART0_RTS/TRGMUX_OUT0}
  - {pin_num: '24', peripheral: LPUART0, signal: RX, pin_signal: ADC0_SE4/PTB0/LPUART0_RX/LPSPI0_PCS0/LPTMR0_ALT3/PWT_IN3}
  - {pin_num: '23', peripheral: LPUART0, signal: TX, pin_signal: ADC0_SE5/PTB1/LPUART0_TX/LPSPI0_SOUT/TCLK0}
  - {pin_num: '9', peripheral: GPIOB, signal: 'GPIO, 7', pin_signal: EXTAL/PTB7/LPI2C0_SCL}
  - {pin_num: '10', peripheral: GPIOB, signal: 'GPIO, 6', pin_signal: XTAL/PTB6/LPI2C0_SDA}
  - {pin_num: '14', peripheral: GPIOC, signal: 'GPIO, 3', pin_signal: ADC0_SE11/ACMP0_IN4/PTC3/FTM0_CH3}
  - {pin_num: '15', peripheral: GPIOC, signal: 'GPIO, 2', pin_signal: ADC0_SE10/ACMP0_IN5/PTC2/FTM0_CH2}
  - {pin_num: '36', peripheral: GPIOC, signal: 'GPIO, 7', pin_signal: TSI0_CH16/PTC7/LPUART1_TX/CAN0_TX}
  - {pin_num: '2', peripheral: GPIOD, signal: 'GPIO, 0', pin_signal: TSI0_CH4/PTD0/FTM0_CH2/TRGMUX_OUT1}
  - {pin_num: '3', peripheral: MSCAN, signal: TX, pin_signal: TSI0_CH0/PTE5/TCLK2/CAN0_TX/EWM_IN}
  - {pin_num: '4', peripheral: MSCAN, signal: RX, pin_signal: TSI0_CH1/PTE4/BUSOUT/CAN0_RX/EWM_OUT_b}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitPins
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void BOARD_InitPins(void)
{
    /* Clock Gate Control: Clock enabled. The current clock selection and divider options are locked. */
    CLOCK_EnableClock(kCLOCK_PortA);
    /* Clock Gate Control: Clock enabled. The current clock selection and divider options are locked. */
    CLOCK_EnableClock(kCLOCK_PortB);
    /* Clock Gate Control: Clock enabled. The current clock selection and divider options are locked. */
    CLOCK_EnableClock(kCLOCK_PortC);
    /* Clock Gate Control: Clock enabled. The current clock selection and divider options are locked. */
    CLOCK_EnableClock(kCLOCK_PortD);
    /* Clock Gate Control: Clock enabled. The current clock selection and divider options are locked. */
    CLOCK_EnableClock(kCLOCK_PortE);

    /* PORTA0 (pin 35) is configured as PTA0 */
    PORT_SetPinMux(PORTA, 0U, kPORT_MuxAsGpio);

    /* PORTA1 (pin 34) is configured as TRGMUX_OUT0 */
    PORT_SetPinMux(PORTA, 1U, kPORT_MuxAlt7);

    /* PORTA2 (pin 33) is configured as LPI2C0_SDA */
    PORT_SetPinMux(PORTA, 2U, kPORT_MuxAlt3);

    /* PORTA3 (pin 32) is configured as LPI2C0_SCL */
    PORT_SetPinMux(PORTA, 3U, kPORT_MuxAlt3);

    /* PORTA4 (pin 44) is configured as SWD_DIO */
    PORT_SetPinMux(PORTA, 4U, kPORT_MuxAlt7);

    /* PORTB0 (pin 24) is configured as LPUART0_RX */
    PORT_SetPinMux(PORTB, 0U, kPORT_MuxAlt2);

    /* PORTB1 (pin 23) is configured as LPUART0_TX */
    PORT_SetPinMux(PORTB, 1U, kPORT_MuxAlt2);

    /* PORTB6 (pin 10) is configured as PTB6 */
    PORT_SetPinMux(PORTB, 6U, kPORT_MuxAsGpio);

    /* PORTB7 (pin 9) is configured as PTB7 */
    PORT_SetPinMux(PORTB, 7U, kPORT_MuxAsGpio);

    /* PORTC2 (pin 15) is configured as PTC2 */
    PORT_SetPinMux(PORTC, 2U, kPORT_MuxAsGpio);

    /* PORTC3 (pin 14) is configured as PTC3 */
    PORT_SetPinMux(PORTC, 3U, kPORT_MuxAsGpio);

    /* PORTC4 (pin 42) is configured as SWD_CLK */
    PORT_SetPinMux(PORTC, 4U, kPORT_MuxAlt7);

    /* PORTC7 (pin 36) is configured as PTC7 */
    PORT_SetPinMux(PORTC, 7U, kPORT_MuxAsGpio);

    /* PORTD0 (pin 2) is configured as PTD0 */
    PORT_SetPinMux(PORTD, 0U, kPORT_MuxAsGpio);

    /* PORTE4 (pin 4) is configured as CAN0_RX */
    PORT_SetPinMux(PORTE, 4U, kPORT_MuxAlt5);

    /* PORTE5 (pin 3) is configured as CAN0_TX */
    PORT_SetPinMux(PORTE, 5U, kPORT_MuxAlt5);
    /* TRGMUX1 Output 2 is selected as EXTOUT0 device trigger input 0 */
    TRGMUX_SetTriggerSource(TRGMUX0, kTRGMUX_ExtOut0_3, kTRGMUX_TriggerInput0, kTRGMUX_SourceTrgmux1Output2);
    /* LPI2C0 Master STOP is selected as CTRL0 device trigger input 2 */
    TRGMUX_SetTriggerSource(TRGMUX1, kTRGMUX_Ctrl0, kTRGMUX_TriggerInput2, kTRGMUX_SourceLpi2c0MasterStop);
}
/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
